global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Linq.Providers;
global using System.Numerics;
global using System.Resources;
global using System.Runtime.CompilerServices;
global using System.Text;
global using Sudoku.Concepts;
global using Sudoku.Concepts.Supersymmetry;
global using Sudoku.Linq;
global using Sudoku.Resources;
global using static Sudoku.SolutionFields;
